# @package _global_
# Large Model Configuration

model:
  embedding_dim: 2 # Larger embedding dimension
  clip_model: "openai/clip-vit-large-patch14"
  freeze_backbone: true
  num_layers: 2
  hidden_dim: 64
